#############################################################################
# Makefile for building: qt_host_installer
# Generated by qmake (3.1) (Qt 5.9.5)
# Project:  qt_host_installer.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile qt_host_installer.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = qt_host_installer130
DISTDIR = /home/tom/qt_host_installer/.tmp/qt_host_installer130
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lz -lQt5Widgets -lQt5Gui -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		utils.cpp \
		io.cpp \
		langselection.cpp \
		updatenotification.cpp \
		supporteddevice.cpp \
		versionselection.cpp \
		preseeddevice.cpp \
		licenseagreement.cpp \
		networksetup.cpp \
		deviceselection.cpp \
		networksettings.cpp \
		advancednetworksetup.cpp \
		wifinetworksetup.cpp \
		downloadprogress.cpp \
		extractprogress.cpp \
		successdialog.cpp \
		preseeder.cpp \
		extractworker.cpp \
		writeimageworker.cpp \
		diskdevice.cpp \
		io_linux.cpp qrc_assets.cpp \
		moc_mainwindow.cpp \
		moc_langselection.cpp \
		moc_updatenotification.cpp \
		moc_versionselection.cpp \
		moc_preseeddevice.cpp \
		moc_licenseagreement.cpp \
		moc_networksetup.cpp \
		moc_deviceselection.cpp \
		moc_advancednetworksetup.cpp \
		moc_wifinetworksetup.cpp \
		moc_downloadprogress.cpp \
		moc_extractprogress.cpp \
		moc_successdialog.cpp \
		moc_extractworker.cpp \
		moc_writeimageworker.cpp
OBJECTS       = main.o \
		mainwindow.o \
		utils.o \
		io.o \
		langselection.o \
		updatenotification.o \
		supporteddevice.o \
		versionselection.o \
		preseeddevice.o \
		licenseagreement.o \
		networksetup.o \
		deviceselection.o \
		networksettings.o \
		advancednetworksetup.o \
		wifinetworksetup.o \
		downloadprogress.o \
		extractprogress.o \
		successdialog.o \
		preseeder.o \
		extractworker.o \
		writeimageworker.o \
		diskdevice.o \
		io_linux.o \
		qrc_assets.o \
		moc_mainwindow.o \
		moc_langselection.o \
		moc_updatenotification.o \
		moc_versionselection.o \
		moc_preseeddevice.o \
		moc_licenseagreement.o \
		moc_networksetup.o \
		moc_deviceselection.o \
		moc_advancednetworksetup.o \
		moc_wifinetworksetup.o \
		moc_downloadprogress.o \
		moc_extractprogress.o \
		moc_successdialog.o \
		moc_extractworker.o \
		moc_writeimageworker.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		qt_host_installer.pro mainwindow.h \
		utils.h \
		langselection.h \
		updatenotification.h \
		supporteddevice.h \
		versionselection.h \
		preseeddevice.h \
		licenseagreement.h \
		networksetup.h \
		deviceselection.h \
		networksettings.h \
		advancednetworksetup.h \
		wifinetworksetup.h \
		downloadprogress.h \
		extractprogress.h \
		successdialog.h \
		preseeder.h \
		extractworker.h \
		writeimageworker.h \
		io.h \
		diskdevice.h main.cpp \
		mainwindow.cpp \
		utils.cpp \
		io.cpp \
		langselection.cpp \
		updatenotification.cpp \
		supporteddevice.cpp \
		versionselection.cpp \
		preseeddevice.cpp \
		licenseagreement.cpp \
		networksetup.cpp \
		deviceselection.cpp \
		networksettings.cpp \
		advancednetworksetup.cpp \
		wifinetworksetup.cpp \
		downloadprogress.cpp \
		extractprogress.cpp \
		successdialog.cpp \
		preseeder.cpp \
		extractworker.cpp \
		writeimageworker.cpp \
		diskdevice.cpp \
		io_linux.cpp
QMAKE_TARGET  = qt_host_installer
DESTDIR       = 
TARGET        = qt_host_installer


first: all
####### Build rules

$(TARGET): ui_mainwindow.h ui_langselection.h ui_updatenotification.h ui_versionselection.h ui_preseeddevice.h ui_licenseagreement.h ui_networksetup.h ui_deviceselection.h ui_advancednetworksetup.h ui_wifinetworksetup.h ui_downloadprogress.h ui_extractprogress.h ui_successdialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qt_host_installer.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		qt_host_installer.pro \
		assets.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Network.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile qt_host_installer.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
qt_host_installer.pro:
assets.qrc:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Network.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile qt_host_installer.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents assets.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h utils.h langselection.h updatenotification.h supporteddevice.h versionselection.h preseeddevice.h licenseagreement.h networksetup.h deviceselection.h networksettings.h advancednetworksetup.h wifinetworksetup.h downloadprogress.h extractprogress.h successdialog.h preseeder.h extractworker.h writeimageworker.h io.h diskdevice.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp utils.cpp io.cpp langselection.cpp updatenotification.cpp supporteddevice.cpp versionselection.cpp preseeddevice.cpp licenseagreement.cpp networksetup.cpp deviceselection.cpp networksettings.cpp advancednetworksetup.cpp wifinetworksetup.cpp downloadprogress.cpp extractprogress.cpp successdialog.cpp preseeder.cpp extractworker.cpp writeimageworker.cpp diskdevice.cpp io_linux.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui langselection.ui updatenotification.ui versionselection.ui preseeddevice.ui licenseagreement.ui networksetup.ui deviceselection.ui advancednetworksetup.ui wifinetworksetup.ui downloadprogress.ui extractprogress.ui successdialog.ui $(DISTDIR)/
	$(COPY_FILE) --parents osmc.ts osmc_da.ts osmc_de.ts osmc_es.ts osmc_fr.ts osmc_nl.ts osmc_ru.ts osmc_sv.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_assets.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_assets.cpp
qrc_assets.cpp: assets.qrc \
		/usr/lib/qt5/bin/rcc \
		icon.png \
		w32-lib/usbit32/usbitcmd.exe \
		w32-lib/usbit32/bs.img \
		resources/spinner.gif \
		resources/SourceSansPro-Regular.ttf \
		resources/forward.png \
		resources/twitter.png \
		resources/logo.png \
		resources/icon_128x128.png \
		resources/backward.png \
		resources/styles.qss \
		resources/fb.png
	/usr/lib/qt5/bin/rcc -name assets assets.qrc -o qrc_assets.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_langselection.cpp moc_updatenotification.cpp moc_versionselection.cpp moc_preseeddevice.cpp moc_licenseagreement.cpp moc_networksetup.cpp moc_deviceselection.cpp moc_advancednetworksetup.cpp moc_wifinetworksetup.cpp moc_downloadprogress.cpp moc_extractprogress.cpp moc_successdialog.cpp moc_extractworker.cpp moc_writeimageworker.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_langselection.cpp moc_updatenotification.cpp moc_versionselection.cpp moc_preseeddevice.cpp moc_licenseagreement.cpp moc_networksetup.cpp moc_deviceselection.cpp moc_advancednetworksetup.cpp moc_wifinetworksetup.cpp moc_downloadprogress.cpp moc_extractprogress.cpp moc_successdialog.cpp moc_extractworker.cpp moc_writeimageworker.cpp
moc_mainwindow.cpp: supporteddevice.h \
		networksettings.h \
		diskdevice.h \
		mainwindow.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/tom/qt_host_installer -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_langselection.cpp: supporteddevice.h \
		ui_langselection.h \
		langselection.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/tom/qt_host_installer -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include langselection.h -o moc_langselection.cpp

moc_updatenotification.cpp: updatenotification.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/tom/qt_host_installer -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include updatenotification.h -o moc_updatenotification.cpp

moc_versionselection.cpp: supporteddevice.h \
		ui_versionselection.h \
		versionselection.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/tom/qt_host_installer -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include versionselection.h -o moc_versionselection.cpp

moc_preseeddevice.cpp: supporteddevice.h \
		ui_preseeddevice.h \
		preseeddevice.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/tom/qt_host_installer -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include preseeddevice.h -o moc_preseeddevice.cpp

moc_licenseagreement.cpp: ui_licenseagreement.h \
		licenseagreement.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/tom/qt_host_installer -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include licenseagreement.h -o moc_licenseagreement.cpp

moc_networksetup.cpp: ui_networksetup.h \
		networksetup.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/tom/qt_host_installer -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include networksetup.h -o moc_networksetup.cpp

moc_deviceselection.cpp: diskdevice.h \
		ui_deviceselection.h \
		deviceselection.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/tom/qt_host_installer -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include deviceselection.h -o moc_deviceselection.cpp

moc_advancednetworksetup.cpp: ui_advancednetworksetup.h \
		advancednetworksetup.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/tom/qt_host_installer -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include advancednetworksetup.h -o moc_advancednetworksetup.cpp

moc_wifinetworksetup.cpp: ui_wifinetworksetup.h \
		wifinetworksetup.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/tom/qt_host_installer -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include wifinetworksetup.h -o moc_wifinetworksetup.cpp

moc_downloadprogress.cpp: downloadprogress.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/tom/qt_host_installer -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include downloadprogress.h -o moc_downloadprogress.cpp

moc_extractprogress.cpp: extractprogress.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/tom/qt_host_installer -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include extractprogress.h -o moc_extractprogress.cpp

moc_successdialog.cpp: successdialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/tom/qt_host_installer -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include successdialog.h -o moc_successdialog.cpp

moc_extractworker.cpp: extractworker.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/tom/qt_host_installer -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include extractworker.h -o moc_extractworker.cpp

moc_writeimageworker.cpp: writeimageworker.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/tom/qt_host_installer -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include writeimageworker.h -o moc_writeimageworker.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_langselection.h ui_updatenotification.h ui_versionselection.h ui_preseeddevice.h ui_licenseagreement.h ui_networksetup.h ui_deviceselection.h ui_advancednetworksetup.h ui_wifinetworksetup.h ui_downloadprogress.h ui_extractprogress.h ui_successdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_langselection.h ui_updatenotification.h ui_versionselection.h ui_preseeddevice.h ui_licenseagreement.h ui_networksetup.h ui_deviceselection.h ui_advancednetworksetup.h ui_wifinetworksetup.h ui_downloadprogress.h ui_extractprogress.h ui_successdialog.h
ui_mainwindow.h: mainwindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_langselection.h: langselection.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic langselection.ui -o ui_langselection.h

ui_updatenotification.h: updatenotification.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic updatenotification.ui -o ui_updatenotification.h

ui_versionselection.h: versionselection.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic versionselection.ui -o ui_versionselection.h

ui_preseeddevice.h: preseeddevice.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic preseeddevice.ui -o ui_preseeddevice.h

ui_licenseagreement.h: licenseagreement.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic licenseagreement.ui -o ui_licenseagreement.h

ui_networksetup.h: networksetup.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic networksetup.ui -o ui_networksetup.h

ui_deviceselection.h: deviceselection.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic deviceselection.ui -o ui_deviceselection.h

ui_advancednetworksetup.h: advancednetworksetup.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic advancednetworksetup.ui -o ui_advancednetworksetup.h

ui_wifinetworksetup.h: wifinetworksetup.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic wifinetworksetup.ui -o ui_wifinetworksetup.h

ui_downloadprogress.h: downloadprogress.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic downloadprogress.ui -o ui_downloadprogress.h

ui_extractprogress.h: extractprogress.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic extractprogress.ui -o ui_extractprogress.h

ui_successdialog.h: successdialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic successdialog.ui -o ui_successdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		supporteddevice.h \
		networksettings.h \
		diskdevice.h \
		utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		supporteddevice.h \
		networksettings.h \
		diskdevice.h \
		ui_mainwindow.h \
		langselection.h \
		ui_langselection.h \
		updatenotification.h \
		versionselection.h \
		ui_versionselection.h \
		preseeddevice.h \
		ui_preseeddevice.h \
		networksetup.h \
		ui_networksetup.h \
		deviceselection.h \
		ui_deviceselection.h \
		utils.h \
		advancednetworksetup.h \
		ui_advancednetworksetup.h \
		wifinetworksetup.h \
		ui_wifinetworksetup.h \
		io.h \
		licenseagreement.h \
		ui_licenseagreement.h \
		downloadprogress.h \
		extractprogress.h \
		successdialog.h \
		preseeder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

utils.o: utils.cpp utils.h \
		supporteddevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o utils.o utils.cpp

io.o: io.cpp utils.h \
		supporteddevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o io.o io.cpp

langselection.o: langselection.cpp langselection.h \
		supporteddevice.h \
		ui_langselection.h \
		utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o langselection.o langselection.cpp

updatenotification.o: updatenotification.cpp updatenotification.h \
		ui_updatenotification.h \
		utils.h \
		supporteddevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o updatenotification.o updatenotification.cpp

supporteddevice.o: supporteddevice.cpp supporteddevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o supporteddevice.o supporteddevice.cpp

versionselection.o: versionselection.cpp versionselection.h \
		supporteddevice.h \
		ui_versionselection.h \
		utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o versionselection.o versionselection.cpp

preseeddevice.o: preseeddevice.cpp preseeddevice.h \
		supporteddevice.h \
		ui_preseeddevice.h \
		utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o preseeddevice.o preseeddevice.cpp

licenseagreement.o: licenseagreement.cpp licenseagreement.h \
		ui_licenseagreement.h \
		utils.h \
		supporteddevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o licenseagreement.o licenseagreement.cpp

networksetup.o: networksetup.cpp networksetup.h \
		ui_networksetup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o networksetup.o networksetup.cpp

deviceselection.o: deviceselection.cpp deviceselection.h \
		diskdevice.h \
		ui_deviceselection.h \
		utils.h \
		supporteddevice.h \
		io.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o deviceselection.o deviceselection.cpp

networksettings.o: networksettings.cpp networksettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o networksettings.o networksettings.cpp

advancednetworksetup.o: advancednetworksetup.cpp advancednetworksetup.h \
		ui_advancednetworksetup.h \
		utils.h \
		supporteddevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o advancednetworksetup.o advancednetworksetup.cpp

wifinetworksetup.o: wifinetworksetup.cpp wifinetworksetup.h \
		ui_wifinetworksetup.h \
		utils.h \
		supporteddevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wifinetworksetup.o wifinetworksetup.cpp

downloadprogress.o: downloadprogress.cpp downloadprogress.h \
		ui_downloadprogress.h \
		utils.h \
		supporteddevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o downloadprogress.o downloadprogress.cpp

extractprogress.o: extractprogress.cpp extractprogress.h \
		ui_extractprogress.h \
		utils.h \
		supporteddevice.h \
		io.h \
		extractworker.h \
		writeimageworker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o extractprogress.o extractprogress.cpp

successdialog.o: successdialog.cpp successdialog.h \
		ui_successdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o successdialog.o successdialog.cpp

preseeder.o: preseeder.cpp preseeder.h \
		networksettings.h \
		mainwindow.h \
		supporteddevice.h \
		diskdevice.h \
		utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o preseeder.o preseeder.cpp

extractworker.o: extractworker.cpp extractworker.h \
		utils.h \
		supporteddevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o extractworker.o extractworker.cpp

writeimageworker.o: writeimageworker.cpp writeimageworker.h \
		io.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o writeimageworker.o writeimageworker.cpp

diskdevice.o: diskdevice.cpp diskdevice.h \
		utils.h \
		supporteddevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o diskdevice.o diskdevice.cpp

io_linux.o: io_linux.cpp io.h \
		utils.h \
		supporteddevice.h \
		diskdevice.h \
		writeimageworker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o io_linux.o io_linux.cpp

qrc_assets.o: qrc_assets.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_assets.o qrc_assets.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_langselection.o: moc_langselection.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_langselection.o moc_langselection.cpp

moc_updatenotification.o: moc_updatenotification.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_updatenotification.o moc_updatenotification.cpp

moc_versionselection.o: moc_versionselection.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_versionselection.o moc_versionselection.cpp

moc_preseeddevice.o: moc_preseeddevice.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_preseeddevice.o moc_preseeddevice.cpp

moc_licenseagreement.o: moc_licenseagreement.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_licenseagreement.o moc_licenseagreement.cpp

moc_networksetup.o: moc_networksetup.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_networksetup.o moc_networksetup.cpp

moc_deviceselection.o: moc_deviceselection.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_deviceselection.o moc_deviceselection.cpp

moc_advancednetworksetup.o: moc_advancednetworksetup.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_advancednetworksetup.o moc_advancednetworksetup.cpp

moc_wifinetworksetup.o: moc_wifinetworksetup.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wifinetworksetup.o moc_wifinetworksetup.cpp

moc_downloadprogress.o: moc_downloadprogress.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_downloadprogress.o moc_downloadprogress.cpp

moc_extractprogress.o: moc_extractprogress.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_extractprogress.o moc_extractprogress.cpp

moc_successdialog.o: moc_successdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_successdialog.o moc_successdialog.cpp

moc_extractworker.o: moc_extractworker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_extractworker.o moc_extractworker.cpp

moc_writeimageworker.o: moc_writeimageworker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_writeimageworker.o moc_writeimageworker.cpp

####### Install
prefix=/usr

install: osmcinstaller
	install -m 0755 osmcinstaller $(prefix)/bin
	install -m 0644 osmcinstaller.desktop $(prefix)/share/applications
	install -d 0755 osmc-installer $(prefix)/share/doc/
	install -m 0644 changelog.gz $(prefix)/share/doc/osmc-installer
	install -d $(prefix)/share/osmc
	install -m 0755 osmcinstaller $(prefix)/share/osmc/
	install -m 0755 qt_host_installer $(prefix)/share/osmc/
	install -m 0644 icon.png $(prefix)/share/osmc/
	install -m 0600 org.osmc.pkexec.run-osmcinstaller.policy $(prefix)/share/polkit-1/actions
	
uninstall:  osmcinstaller
	rm $(prefix)/bin/osmcinstaller
	rm $(prefix)/share/applications/osmcinstaller.desktop
	rm -r $(prefix)/share/doc/osmc-installer
	rm -r $(prefix)/share/osmc
	rm $(prefix)/share/polkit-1/actions/org.osmc.pkexec.run-osmcinstaller.policy

FORCE:

