#!/usr/bin/env bash
Xaxis=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f1)
OS=$(awk -F= '/^NAME/{print $2}' /etc/os-release)
if [ $Xaxis \> 1920 ];
then
        SCALE="QT_SCALE_FACTOR=1 QT_AUTO_SCREEN_SCALE_FACTOR=0 QT_SCREEN_SCALE_FACTORS=2"
else
        SCALE=""
fi

cp /tmp/.mount_osmc*/usr/share/osmc/qt_host_installer $PWD
chmod 777 qt_host_installer
if [[ $OS == *"SUSE"* ]]; then
        CMD="pkexec env QT_X11_NO_MITSHM=1 DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY $SCALE $PWD/qt_host_installer "$@"";
        else CMD=$(xhost si:localuser:root && pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY $SCALE $PWD/qt_host_installer "$@" && xhost -si:localuser:root);
fi
$CMD
rm -rf $PWD/qt_host_installer
